/**
 * curl.ts — cURL shell snippet generator.
 * Uses single-quote escaping with `'\''` for embedded single quotes.
 * Uses --data-raw (no @-file processing). Adds --insecure comment for reference.
 * Handles binary body via base64 + shell decode comment.
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function shEscape(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'";
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('# cURL — generated by ProxiFlare');
  lines.push('# Remove --insecure if the server has a valid certificate');
  lines.push('');

  const headerFlags = har.headers
    .map(h => `  --header ${shEscape(`${h.name}: ${h.value}`)} \\`)
    .join('\n');

  let bodyFlag = '';
  if (har.postData) {
    if (har.postData.isBinary) {
      lines.push(`# Binary body — decode before sending`);
      const b64 = btoa(har.postData.text);
      bodyFlag = `  --data-raw $(echo ${shEscape(b64)} | base64 -d) \\`;
    } else {
      bodyFlag = `  --data-raw ${shEscape(har.postData.text)} \\`;
    }
  }

  const methodFlag = har.method !== 'GET'
    ? `  --request ${shEscape(har.method)} \\\n`
    : '';

  lines.push(
    `curl --insecure \\`,
    ...( methodFlag ? [methodFlag.trimEnd()] : [] ),
    ...( headerFlags ? [headerFlags] : [] ),
    ...( bodyFlag    ? [bodyFlag]    : [] ),
    `  ${shEscape(har.url)}`,
  );

  return lines.join('\n');
}
