/**
 * go-nethttp.ts — Go net/http snippet generator.
 * Uses backtick raw string literals for body (backticks escaped via concatenation).
 * TLS skip: crypto/tls InsecureSkipVerify shown as comment.
 * Binary bodies use base64.StdEncoding.DecodeString.
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function goStr(s: string): string {
  return '"' + s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    + '"';
}

function goRaw(s: string): string {
  // backtick raw literal; if string has backticks, concatenate around them
  if (!s.includes('`')) return '`' + s + '`';
  return s.split('`').map(part => '`' + part + '`').join(' + \"`\" + ');
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('// Go: net/http — generated by ProxiFlare');
  lines.push('package main');
  lines.push('');
  lines.push('import (');
  lines.push('\t"fmt"');
  lines.push('\t"io"');
  lines.push('\t"net/http"');
  lines.push('\t"strings"');
  if (har.postData?.isBinary) lines.push('\t"encoding/base64"');
  lines.push(')');
  lines.push('');

  lines.push('func main() {');
  lines.push(`\t// To skip TLS verification, configure an http.Client with a custom Transport:`);
  lines.push(`\t// tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}`);
  lines.push(`\t// client := &http.Client{Transport: tr}`);
  lines.push('');

  let bodyExpr = 'nil';
  if (har.postData) {
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push(`\t// Binary body — decoded from base64`);
      lines.push(`\tbody64 := ${goStr(b64)}`);
      lines.push(`\tbodyBytes, _ := base64.StdEncoding.DecodeString(body64)`);
      lines.push(`\tbodyReader := strings.NewReader(string(bodyBytes))`);
      bodyExpr = 'bodyReader';
    } else {
      lines.push(`\tbody := ${goRaw(har.postData.text)}`);
      lines.push(`\tbodyReader := strings.NewReader(body)`);
      bodyExpr = 'bodyReader';
    }
    lines.push('');
  }

  lines.push(`\treq, err := http.NewRequest(${goStr(har.method)}, ${goStr(har.url)}, ${bodyExpr})`);
  lines.push('\tif err != nil { panic(err) }');
  lines.push('');

  for (const h of har.headers) {
    lines.push(`\treq.Header.Set(${goStr(h.name)}, ${goStr(h.value)})`);
  }

  lines.push('');
  lines.push('\tclient := &http.Client{}');
  lines.push('\tresp, err := client.Do(req)');
  lines.push('\tif err != nil { panic(err) }');
  lines.push('\tdefer resp.Body.Close()');
  lines.push('\tbody2, _ := io.ReadAll(resp.Body)');
  lines.push('\tfmt.Println(resp.StatusCode, string(body2[:min(len(body2), 500)]))');
  lines.push('}');
  lines.push('');
  lines.push('func min(a, b int) int { if a < b { return a }; return b }');

  return lines.join('\n');
}
