/**
 * java-okhttp.ts — Java OkHttp3 snippet generator.
 * String body uses concatenation with \n for multilines; " and \ escaped.
 * SSLContext unsafe config shown as comment.
 * Binary bodies: Base64.getDecoder().decode().
 * Requires: implementation 'com.squareup.okhttp3:okhttp:4.12.0'
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function jStr(s: string): string {
  return '"' + s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    + '"';
}

function jMultilineStr(s: string): string {
  const lines = s.split('\n');
  if (lines.length === 1) return jStr(s);
  return lines.map((l, i) =>
    i === 0 ? jStr(l) : `    + "\\n" + ${jStr(l)}`
  ).join('\n');
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('// Java: OkHttp3 — generated by ProxiFlare');
  lines.push('// Requires: com.squareup.okhttp3:okhttp:4.12.0');
  lines.push('');
  lines.push('import okhttp3.*;');
  lines.push('import java.io.IOException;');
  if (har.postData?.isBinary) lines.push('import java.util.Base64;');
  lines.push('');
  lines.push('public class Main {');
  lines.push('    public static void main(String[] args) throws IOException {');
  lines.push(`        String url = ${jStr(har.url)};`);
  lines.push('');

  lines.push('        // To skip TLS: configure OkHttpClient with custom SSLSocketFactory');
  lines.push('        OkHttpClient client = new OkHttpClient();');
  lines.push('');

  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    lines.push(`        MediaType mediaType = MediaType.parse(${jStr(har.postData.mimeType)});`);
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push(`        // Binary body — decoded from base64`);
      lines.push(`        byte[] bodyBytes = Base64.getDecoder().decode(${jStr(b64)});`);
      lines.push(`        RequestBody body = RequestBody.create(bodyBytes, mediaType);`);
    } else if (mime.includes('application/json') || mime.includes('text/')) {
      const bodyStr = jMultilineStr(har.postData.text);
      lines.push(`        String bodyStr = ${bodyStr};`);
      lines.push(`        RequestBody body = RequestBody.create(bodyStr, mediaType);`);
    } else {
      const bodyStr = jMultilineStr(har.postData.text);
      lines.push(`        String bodyStr = ${bodyStr};`);
      lines.push(`        RequestBody body = RequestBody.create(bodyStr, mediaType);`);
    }
    lines.push('');
  }

  lines.push('        Request request = new Request.Builder()');
  lines.push(`            .url(url)`);
  lines.push(`            .method(${jStr(har.method)}, ${har.postData ? 'body' : 'null'})`);
  for (const h of har.headers) {
    lines.push(`            .addHeader(${jStr(h.name)}, ${jStr(h.value)})`);
  }
  lines.push('            .build();');
  lines.push('');
  lines.push('        try (Response response = client.newCall(request).execute()) {');
  lines.push('            System.out.println(response.code());');
  lines.push('            String respBody = response.body() != null ? response.body().string() : "";');
  lines.push('            System.out.println(respBody.substring(0, Math.min(respBody.length(), 500)));');
  lines.push('        }');
  lines.push('    }');
  lines.push('}');

  return lines.join('\n');
}
