/**
 * node-fetch.ts — Node.js native fetch snippet (Web Streams body).
 * Requires Node 18+. Uses globalThis.fetch (no import needed since Node 18).
 * TLS: process.env.NODE_TLS_REJECT_UNAUTHORIZED workaround noted in comment.
 * Handles JSON, text, binary (Buffer from base64) bodies.
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function jsStr(s: string): string {
  return '"' + s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/`/g, '\\`')
    + '"';
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('// Node.js native fetch — generated by ProxiFlare');
  lines.push('// Requires Node 18+. For self-signed certs, set NODE_TLS_REJECT_UNAUTHORIZED=0');
  lines.push('');
  lines.push(`const url = ${jsStr(har.url)};`);
  lines.push('');

  if (har.headers.length > 0) {
    lines.push('const headers = {');
    for (const h of har.headers) {
      lines.push(`  ${jsStr(h.name)}: ${jsStr(h.value)},`);
    }
    lines.push('};');
  } else {
    lines.push('const headers = {};');
  }
  lines.push('');

  let bodyDecl = '';
  if (har.postData) {
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push('// Binary body — decoded from base64');
      lines.push(`const body = Buffer.from(${jsStr(b64)}, 'base64');`);
      bodyDecl = 'body,';
    } else {
      lines.push(`const body = ${jsStr(har.postData.text)};`);
      bodyDecl = 'body,';
    }
    lines.push('');
  }

  lines.push(`const response = await fetch(url, {`);
  lines.push(`  method: ${jsStr(har.method)},`);
  lines.push(`  headers,`);
  if (bodyDecl) lines.push(`  ${bodyDecl}`);
  lines.push(`});`);
  lines.push('');
  lines.push('const text = await response.text();');
  lines.push("console.log(response.status, text.slice(0, 500));");

  return lines.join('\n');
}
