/**
 * node-axios.ts — Node.js axios snippet generator.
 * Uses axios with httpsAgent to disable TLS verify (commented out by default).
 * Handles JSON auto-parsing, form data, binary via Buffer from base64.
 * Requires: npm install axios
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function jsStr(s: string): string {
  return '"' + s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    + '"';
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('// Node.js: axios — generated by ProxiFlare');
  lines.push("// Requires: npm install axios");
  lines.push("const axios = require('axios');");
  lines.push("// const https = require('https');");
  lines.push("// const agent = new https.Agent({ rejectUnauthorized: false }); // disable TLS verify");
  lines.push('');
  lines.push(`const url = ${jsStr(har.url)};`);
  lines.push('');

  if (har.headers.length > 0) {
    lines.push('const headers = {');
    for (const h of har.headers) {
      lines.push(`  ${jsStr(h.name)}: ${jsStr(h.value)},`);
    }
    lines.push('};');
  } else {
    lines.push('const headers = {};');
  }
  lines.push('');

  let dataDecl = 'undefined';
  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push('// Binary body — decoded from base64');
      lines.push(`const data = Buffer.from(${jsStr(b64)}, 'base64');`);
      dataDecl = 'data';
    } else if (mime.includes('application/json')) {
      try {
        JSON.parse(har.postData.text);
        lines.push(`const data = ${har.postData.text}; // already valid JSON`);
        dataDecl = 'data';
      } catch {
        lines.push(`const data = ${jsStr(har.postData.text)};`);
        dataDecl = 'data';
      }
    } else {
      lines.push(`const data = ${jsStr(har.postData.text)};`);
      dataDecl = 'data';
    }
    lines.push('');
  }

  lines.push(`const response = await axios({`);
  lines.push(`  method: ${jsStr(har.method.toLowerCase())},`);
  lines.push(`  url,`);
  lines.push(`  headers,`);
  if (dataDecl !== 'undefined') lines.push(`  data: ${dataDecl},`);
  lines.push(`  // httpsAgent: agent, // uncomment to disable TLS verify`);
  lines.push(`});`);
  lines.push('');
  lines.push("console.log(response.status, JSON.stringify(response.data).slice(0, 500));");

  return lines.join('\n');
}
