/**
 * php-guzzle.ts — PHP Guzzle HTTP client snippet generator.
 * verify => false shown as comment. Uses array for headers and body options.
 * JSON bodies auto-detected and sent via 'json' key. Binary via base64_decode.
 * Requires: composer require guzzlehttp/guzzle
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function phpStr(s: string): string {
  return "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('<?php');
  lines.push('// PHP: Guzzle — generated by ProxiFlare');
  lines.push("// Requires: composer require guzzlehttp/guzzle");
  lines.push("use GuzzleHttp\\Client;");
  lines.push('');
  lines.push(`$url = ${phpStr(har.url)};`);
  lines.push('');

  lines.push('$headers = [');
  for (const h of har.headers) {
    lines.push(`    ${phpStr(h.name)} => ${phpStr(h.value)},`);
  }
  lines.push('];');
  lines.push('');

  lines.push(`$client = new Client([`);
  lines.push(`    // 'verify' => false, // disable TLS certificate verification`);
  lines.push(`]);`);
  lines.push('');

  const options: string[] = [`    'headers' => $headers,`];

  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push('// Binary body — decoded from base64 before sending');
      lines.push(`$body = base64_decode(${phpStr(b64)});`);
      options.push(`    'body' => $body,`);
    } else if (mime.includes('application/json')) {
      try {
        const parsed = JSON.parse(har.postData.text);
        // emit as PHP array literal
        lines.push(`$payload = json_decode(${phpStr(JSON.stringify(parsed))}, true);`);
        options.push(`    'json' => $payload,`);
      } catch {
        options.push(`    'body' => ${phpStr(har.postData.text)},`);
      }
    } else if (mime.includes('application/x-www-form-urlencoded')) {
      lines.push('$form = [');
      for (const q of har.queryString) {
        lines.push(`    ${phpStr(q.name)} => ${phpStr(q.value)},`);
      }
      lines.push('];');
      options.push(`    'form_params' => $form,`);
    } else {
      options.push(`    'body' => ${phpStr(har.postData.text)},`);
    }
    lines.push('');
  }

  lines.push(`$response = $client->request(${phpStr(har.method)}, $url, [`);
  for (const opt of options) lines.push(opt);
  lines.push(']);');
  lines.push('');
  lines.push('echo $response->getStatusCode() . PHP_EOL;');
  lines.push('echo substr($response->getBody()->getContents(), 0, 500);');

  return lines.join('\n');
}
