/**
 * php-curl.ts — PHP cURL extension snippet generator.
 * Uses CURLOPT_SSL_VERIFYPEER / VERIFYHOST commented out by default.
 * Body uses nowdoc (<<<'EOD') to avoid any variable interpolation.
 * Handles JSON, form, and binary (base64_decode).
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function phpStr(s: string): string {
  return "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('<?php');
  lines.push('// PHP: cURL — generated by ProxiFlare');
  lines.push('');
  lines.push(`$url = ${phpStr(har.url)};`);
  lines.push('');

  lines.push('$headers = [');
  for (const h of har.headers) {
    lines.push(`    ${phpStr(`${h.name}: ${h.value}`)},`);
  }
  lines.push('];');
  lines.push('');

  const ch = '$ch';
  lines.push(`${ch} = curl_init();`);
  lines.push(`curl_setopt(${ch}, CURLOPT_URL, $url);`);
  lines.push(`curl_setopt(${ch}, CURLOPT_RETURNTRANSFER, true);`);
  lines.push(`curl_setopt(${ch}, CURLOPT_HTTPHEADER, $headers);`);

  if (har.method !== 'GET') {
    lines.push(`curl_setopt(${ch}, CURLOPT_CUSTOMREQUEST, ${phpStr(har.method)});`);
  }

  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push('// Binary body — decoded from base64 before sending');
      lines.push(`$body = base64_decode(${phpStr(b64)});`);
      lines.push(`curl_setopt(${ch}, CURLOPT_POSTFIELDS, $body);`);
    } else if (mime.includes('application/x-www-form-urlencoded')) {
      lines.push(`curl_setopt(${ch}, CURLOPT_POSTFIELDS, ${phpStr(har.postData.text)});`);
    } else {
      // nowdoc for body to avoid any PHP interpolation
      lines.push(`$body = <<<'EOD'`);
      lines.push(har.postData.text);
      lines.push('EOD;');
      lines.push(`curl_setopt(${ch}, CURLOPT_POSTFIELDS, $body);`);
    }
  }

  lines.push(`// curl_setopt(${ch}, CURLOPT_SSL_VERIFYPEER, false); // disable TLS verify`);
  lines.push(`// curl_setopt(${ch}, CURLOPT_SSL_VERIFYHOST, false);`);
  lines.push('');
  lines.push(`$response = curl_exec(${ch});`);
  lines.push(`$httpCode = curl_getinfo(${ch}, CURLINFO_HTTP_CODE);`);
  lines.push(`curl_close(${ch});`);
  lines.push('');
  lines.push('echo $httpCode . PHP_EOL . substr($response, 0, 500);');

  return lines.join('\n');
}
