/**
 * python-httpx.ts — Python `httpx` library snippet generator.
 * Async variant (httpx.AsyncClient). verify=False comment included.
 * Handles JSON, form, binary (base64), and raw bodies.
 * Requires: pip install httpx
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function pyStr(s: string): string {
  return '"' + s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
    + '"';
}

function pyDict(pairs: { name: string; value: string }[], indent = '    '): string {
  if (pairs.length === 0) return '{}';
  const rows = pairs.map(p => `${indent}${pyStr(p.name)}: ${pyStr(p.value)},`);
  return '{\n' + rows.join('\n') + '\n}';
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('# Python: httpx (async) — generated by ProxiFlare');
  lines.push('import asyncio');
  lines.push('import httpx');
  lines.push('');
  lines.push(`url = ${pyStr(har.url)}`);
  lines.push('');
  lines.push(`headers = ${pyDict(har.headers)}`);
  lines.push('');

  let bodyLines: string[] = [];
  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    if (har.postData.isBinary) {
      lines.push('import base64');
      const b64 = btoa(har.postData.text);
      lines.push('# Binary body — decoded from base64 before sending');
      lines.push(`data = base64.b64decode(${pyStr(b64)})`);
      bodyLines = ['content=data,'];
    } else if (mime.includes('application/json')) {
      try {
        JSON.parse(har.postData.text);
        lines.push('import json');
        lines.push(`payload = json.loads(${pyStr(har.postData.text)})`);
        bodyLines = ['json=payload,'];
      } catch {
        lines.push(`data = ${pyStr(har.postData.text)}`);
        bodyLines = ['content=data.encode(),'];
      }
    } else if (mime.includes('application/x-www-form-urlencoded')) {
      lines.push(`form = ${pyDict(har.queryString)}`);
      bodyLines = ['data=form,'];
    } else {
      lines.push(`data = ${pyStr(har.postData.text)}`);
      bodyLines = ['content=data.encode(),'];
    }
    lines.push('');
  }

  const method = har.method.toLowerCase();
  lines.push('async def main():');
  lines.push(
    `    async with httpx.AsyncClient(verify=False) as client:`,
    `        # verify=False disables TLS verification — use verify=True in production`,
    `        response = await client.${method}(`,
    `            url,`,
    `            headers=headers,`,
    ...bodyLines.map(l => `            ${l}`),
    `        )`,
    `        print(response.status_code, response.text[:500])`,
  );
  lines.push('');
  lines.push('asyncio.run(main())');

  return lines.join('\n');
}
