/**
 * python-requests.ts — Python `requests` library snippet generator.
 * verify=False is OFF by default (comment explains). Uses repr-style escaping.
 * Handles JSON body (auto-parse), form-urlencoded, and binary (base64 decode).
 * Requires: pip install requests
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function pyStr(s: string): string {
  return '"' + s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
    + '"';
}

function pyDict(pairs: { name: string; value: string }[], indent = '    '): string {
  if (pairs.length === 0) return '{}';
  const rows = pairs.map(p => `${indent}${pyStr(p.name)}: ${pyStr(p.value)},`);
  return '{\n' + rows.join('\n') + '\n}';
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('# Python: requests — generated by ProxiFlare');
  lines.push('import requests');
  lines.push('');
  lines.push(`url = ${pyStr(har.url)}`);
  lines.push('');

  lines.push(`headers = ${pyDict(har.headers)}`);
  lines.push('');

  let bodyLines: string[] = [];
  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    if (har.postData.isBinary) {
      lines.push('import base64');
      const b64 = btoa(har.postData.text);
      lines.push(`# Binary body — decoded from base64 before sending`);
      lines.push(`data = base64.b64decode(${pyStr(b64)})`);
      bodyLines = ['data=data,'];
    } else if (mime.includes('application/json')) {
      try {
        const parsed = JSON.parse(har.postData.text);
        lines.push(`import json`);
        lines.push(`payload = json.loads(${pyStr(har.postData.text)})`);
        bodyLines = ['json=payload,'];
        void parsed;
      } catch {
        lines.push(`data = ${pyStr(har.postData.text)}`);
        bodyLines = ['data=data,'];
      }
    } else if (mime.includes('application/x-www-form-urlencoded')) {
      const params = har.queryString.length > 0 ? har.queryString : [];
      lines.push(`data = ${pyDict(params)}`);
      bodyLines = ['data=data,'];
    } else {
      lines.push(`data = ${pyStr(har.postData.text)}`);
      bodyLines = ['data=data,'];
    }
    lines.push('');
  }

  const method = har.method.toLowerCase();
  lines.push(
    `response = requests.${method}(`,
    `    url,`,
    `    headers=headers,`,
    ...bodyLines.map(l => `    ${l}`),
    `    verify=False,  # set verify=True or path to CA bundle in production`,
    `)`,
  );
  lines.push('');
  lines.push('print(response.status_code, response.text[:500])');

  return lines.join('\n');
}
