/**
 * rust-reqwest.ts — Rust reqwest (blocking) snippet generator.
 * Uses r#""# raw string literals for body; more hashes added if body contains "#.
 * danger_accept_invalid_certs() shown as comment.
 * Binary bodies: base64 crate decode. JSON: serde_json::from_str.
 * Requires: reqwest = { features = ["blocking"] }, serde_json, base64 in Cargo.toml
 */

import type { InspectEntry } from './har.ts';
import { toHar } from './har.ts';

function rustStr(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
}

function rustRaw(s: string): string {
  // pick minimum number of hashes so the body can't accidentally close the literal
  let hashes = 0;
  while (s.includes('"' + '#'.repeat(hashes))) hashes++;
  const h = '#'.repeat(hashes);
  return `r${h}"${s}"${h}`;
}

export function generate(entry: InspectEntry): string {
  const har = toHar(entry);
  const lines: string[] = [];

  lines.push('// Rust: reqwest (blocking) — generated by ProxiFlare');
  lines.push('// Cargo.toml: reqwest = { version = "0.12", features = ["blocking"] }');
  if (har.postData?.isBinary) {
    lines.push('// Cargo.toml: base64 = "0.22"');
  }
  const hasMime = har.postData?.mimeType.toLowerCase().includes('application/json');
  if (hasMime) lines.push('// Cargo.toml: serde_json = "1"');
  lines.push('');
  lines.push('fn main() -> Result<(), Box<dyn std::error::Error>> {');
  lines.push(`    let url = ${rustStr(har.url)};`);
  lines.push('');

  lines.push('    let client = reqwest::blocking::Client::builder()');
  lines.push('        // .danger_accept_invalid_certs(true) // disable TLS verify');
  lines.push('        .build()?;');
  lines.push('');

  lines.push('    let mut req = client');
  lines.push(`        .${har.method.toLowerCase()}(url)`);

  for (const h of har.headers) {
    lines.push(`        .header(${rustStr(h.name)}, ${rustStr(h.value)})`);
  }

  if (har.postData) {
    const mime = har.postData.mimeType.toLowerCase();
    if (har.postData.isBinary) {
      const b64 = btoa(har.postData.text);
      lines.push('        // Binary body — decoded from base64');
      lines.push(`        .body(base64::decode(${rustStr(b64)}).unwrap())`);
    } else if (mime.includes('application/json')) {
      lines.push(`        .body(${rustRaw(har.postData.text)})`);
    } else {
      lines.push(`        .body(${rustRaw(har.postData.text)})`);
    }
  }

  lines.push('        ;');
  lines.push('');
  lines.push('    let _ = &mut req; // suppress unused warning');
  lines.push('    let resp = req.send()?;');
  lines.push('    println!("{}", resp.status());');
  lines.push('    let body = resp.text()?;');
  lines.push('    println!("{}", &body[..body.len().min(500)]);');
  lines.push('    Ok(())');
  lines.push('}');

  return lines.join('\n');
}
